hello/urls.py
from django.urls import path

from .views import *


app_name = 'poll'
urlpatterns = [
    path('', PollsIndex.as_view(), name='index'),
    path('<int:pk>/', PollDetail.as_view(), name='detail'),
    path('<int:pk>/result', PollResult.as_view(), name='result'),
    path('<int:question_id>/vote/', vote, name='vote'),
]

hl_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('home/', include('hello.urls')),
    path('admin/', admin.site.urls),
]

hello/models.py
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    opened = models.BooleanField(default=True)

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = "Опрос"
        verbose_name_plural = "Опросы"
        ordering = ['-pub_date', 'question_text']


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"
        ordering = ['-votes', 'choice_text']

hello/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView, DetailView

from .models import *


class PollsIndex(ListView):
    model = Question
    template_name = 'hello/index.html'
    context_object_name = 'latest_question_list'
    extra_context = {'title': 'Главная страница'}

    def get_queryset(self):
        return Question.objects.filter(opened=True)


class PollDetail(DetailView):
    model = Question
    template_name = 'hello/detail.html'
    extra_context = {'title': 'Страница опроса'}


class PollResult(DetailView):
    model = Question
    template_name = 'hello/result.html'
    extra_context = {'title': 'Результаты опроса'}


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'hello/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('poll:result', args=(question_id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
</head>
<body>
    {%block content%}

    {% endblock %}
</body>
</html>

templates/hello/detail.html
{%extends 'base.html' %}


{% block content%}

<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Голосовать">
</form>

{% endblock%}

templates/hello/index.html
{%extends 'base.html' %}


{% block content%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'poll:detail' question.pk %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock%}

templates/hello/result.html
{%extends 'base.html' %}


{% block content%}

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Голосовать еще раз?</a><br>

<a href="{% url 'poll:index' %}">На главную</a>

{% endblock%}